### ISSUE TITLE
Add Vodafone Gigabox (Ireland) to supported devices

### ISSUE THREAD

**Issue by shanemeagher** [chemelli74/aiovodafone#59]
Using the Vodafone Station Integration in Home Assistant, I was able to add my Vodafone Gigabox router to my system. This is the router supplied by Vodafone Ireland for their broadband installs. It's model is listed as `SHG3000` on the label on the underside of the router so would appear to be the same as Vodafone Power Station that is on the supported list.

From initial usage, all functionality seems to be working.

It would be nice to have it listed as a supported device, and as a follow on, Vodafone Gigabox added as a Virtual Integration in Home Assistant to point to the Vodafone Station integration.

Let me know if you need any additional info or testing.

### Additional Info:
From the router's Support pages:
| Key | Value|
|--------|--------|
| Product Name | Vodafone Gigabox |
| Firmware Version | XS_4.1.00.01 |
| Bootloader Version | 5.0.0.0 |
| Hardware Type & Version | VOX30R1 | 

Querying the UpnP interface, it's called a `Sercomm VOX30`.

**Comment by chemelli74** [comment]
Please be so kind to open a PR for updating docs here: https://github.com/home-assistant/home-assistant.io/pulls

**Comment by shanemeagher** [comment]
Let me know if this was enough.
